spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test1?useSSL=true
    username: root
    password: root
    tomcat:
      max-active: 20
      time-between-eviction-runs-millis: 300000
      max-wait: 120000
    dbcp2:
      initial-size: 5
  thymeleaf:
    cache: false
mybatis:
  type-aliases-package: com.example.springbootmybatis.domain
server:
  context-path: /springboot

